Models/Sach.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.ChiTietTheLoai = new HashSet<ChiTietTheLoai>();
            this.DanhGiaSach = new HashSet<DanhGiaSach>();
            this.DanhSachYeuThich = new HashSet<DanhSachYeuThich>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public string TacGia { get; set; }
        public Nullable<int> NamXB { get; set; }
        public Nullable<int> LanXB { get; set; }
        public string TomTat { get; set; }
        public string TongSoTrang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> Tap { get; set; }
        public Nullable<int> TongSoTap { get; set; }
        public Nullable<double> GiaTriSach { get; set; }
        public Nullable<double> GiamGia { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public string GioiThieu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string Anh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietTheLoai> ChiTietTheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaSach> DanhGiaSach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachYeuThich> DanhSachYeuThich { get; set; }
    }
}

Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;

namespace BookStore.Controllers
{
    public class SachController : Controller
    {
        BookStoreEntities db = new BookStoreEntities();
        // GET: Sach
        public ActionResult TrangChu()
        {
            List<Sach> lstSach = db.Sach.Where(n => n.TrangThai != 0 && n.GiamGia > 0).OrderByDescending(n => n.GiamGia).ToList(); // list sách theo thự tự mới đến cũ
            List<double?> giasach = new List<double?>(); // danh sách giá sách sau khi tính giảm giá

            foreach (var item in lstSach)
            {
                if (item.GiamGia != 0)
                {
                    double? gia = item.GiaTriSach - item.GiaTriSach * item.GiamGia / 100;
                    giasach.Add(gia);
                }
                else
                {
                    giasach.Add(item.GiaTriSach);
                }
            }
            ViewBag.GiaSach = giasach;

            // top 8 sách mới nhất
            List<Sach> lstSachMoi = db.Sach.Where(n => n.TrangThai != 0).OrderByDescending(n => n.MaSach).Take(8).ToList(); // list sách theo thự tự mới đến cũ
            ViewBag.lstSachMoi = lstSachMoi;

            List<double?> giasachmoi = new List<double?>(); // danh sách giá 

            foreach (var item in lstSachMoi)
            {
                if (item.GiamGia != 0)
                {
                    double? gia = item.GiaTriSach - item.GiaTriSach * item.GiamGia / 100;
                    giasachmoi.Add(gia);
                }
                else
                {
                    giasachmoi.Add(item.GiaTriSach);
                }
            }
            ViewBag.GiaSachMoi = giasachmoi;
            //
            if (lstSach.Count == 0 || lstSachMoi.Count == 0)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(lstSach);
        }
        public PartialViewResult TheLoaiPartial()
        {
            return PartialView(db.TheLoai.ToList());
        }

        public ActionResult DanhSach()
        {
            List<Sach> lstSach = db.Sach.Where(n => n.TrangThai != 0).OrderByDescending(n => n.MaSach).ToList(); // list sách theo thự tự mới đến cũ
            List<double?> giasach = new List<double?>(); // danh sách giá 

            foreach(var item in lstSach)
            {
                if(item.GiamGia != 0)
                {
                    double? gia = item.GiaTriSach - item.GiaTriSach * item.GiamGia / 100;
                    giasach.Add(gia);
                }
                else
                {
                    giasach.Add(item.GiaTriSach);
                }
            }
            ViewBag.GiaSach = giasach;
            if (lstSach.Count == 0)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.lstSach = db.Sach.ToList();
            return View(lstSach);
        }

        public ViewResult SanPhamTheoLoai(int MaTheLoai)
        {
            TheLoai lsp = db.TheLoai.SingleOrDefault(n => n.MaTheLoai == MaTheLoai);

            if (lsp == null)
            {   
                Response.StatusCode = 404;
                return null;
            }
            List<ChiTietTheLoai> lstCTTheLoai = db.ChiTietTheLoai.Where(n => n.MaTheLoai == MaTheLoai).OrderByDescending(n => n.MaSach).ToList();

            List<Sach> lstSach = new List<Sach>();
            foreach(var item in lstCTTheLoai)
            {
                Sach s = db.Sach.SingleOrDefault(n => n.MaSach == item.MaSach && n.TrangThai != 0);
                if (s != null)
                {
                    lstSach.Add(s);
                }
            };

            List<double?> giasach = new List<double?>(); // danh sách giá 

            foreach (var item in lstSach)
            {
                if (item.GiamGia != 0)
                {
                    double? gia = item.GiaTriSach - item.GiaTriSach * item.GiamGia / 100;
                    giasach.Add(gia);
                }
                else
                {
                    giasach.Add(item.GiaTriSach);
                }
            }
            ViewBag.GiaSach = giasach;
            if (lstSach.Count == 0)
            {
                ViewBag.lstSanPham = "Không có sách nào thuộc thể loại này";
            }
            //ViewBag.MaTheLoai = MaTheLoai;
            ViewBag.TenTheLoai = db.TheLoai.SingleOrDefault(n => n.MaTheLoai == MaTheLoai).TenTheLoai;
            //ViewBag.lstSanPham = db.TheLoai.ToList();
            return View(lstSach);
        }

        public ActionResult ChiTietSach(int MaSach)
        {
            Sach sach = db.Sach.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            double? giasach = sach.GiaTriSach; 
            if (sach.GiamGia != 0)
            {
                giasach = sach.GiaTriSach - sach.GiaTriSach * sach.GiamGia / 100;
            }
            ViewBag.GiaSach = giasach;
            return View(sach);
        }

    }
}

Views/Sach/DanhSach.cshtml
@using BookStore.Models;
@model List<Sach>
@{
    ViewBag.Title = "Danh Sách";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="site-content space-bottom-3" id="content">
    <div class="container">
        <div class="row">
            <div id="primary" class="content-area order-2">
                @*<div class="shop-control-bar d-lg-flex justify-content-between align-items-center mb-5 text-center text-md-left">

                    <div class="shop-control-bar__right d-md-flex align-items-center">
                        <form class="number-of-items ml-md-4 mb-4 m-md-0 d-none d-xl-block" method="get">

                            <select class="js-select selectpicker dropdown-select orderby" name="orderby" data-style="border-bottom shadow-none outline-none py-2" data-width="fit">
                                <option value="show10">Show 10</option>
                                <option value="show15">Show 15</option>
                                <option value="show20" selected="selected">Show 20</option>
                                <option value="show25">Show 25</option>
                                <option value="show30">Show 30</option>
                            </select>

                        </form>
                        <ul class="nav nav-tab ml-lg-4 justify-content-center justify-content-md-start ml-md-auto" id="pills-tab" role="tablist">
                            <li class="nav-item border">
                                <a class="nav-link p-0 height-38 width-38 justify-content-center d-flex align-items-center active" id="pills-one-example1-tab" data-toggle="pill" href="#pills-one-example1" role="tab" aria-controls="pills-one-example1" aria-selected="true">
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="17px" height="17px">
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M-0.000,0.000 L3.000,0.000 L3.000,3.000 L-0.000,3.000 L-0.000,0.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M7.000,0.000 L10.000,0.000 L10.000,3.000 L7.000,3.000 L7.000,0.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M14.000,0.000 L17.000,0.000 L17.000,3.000 L14.000,3.000 L14.000,0.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M-0.000,7.000 L3.000,7.000 L3.000,10.000 L-0.000,10.000 L-0.000,7.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M7.000,7.000 L10.000,7.000 L10.000,10.000 L7.000,10.000 L7.000,7.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M14.000,7.000 L17.000,7.000 L17.000,10.000 L14.000,10.000 L14.000,7.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M-0.000,14.000 L3.000,14.000 L3.000,17.000 L-0.000,17.000 L-0.000,14.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M7.000,14.000 L10.000,14.000 L10.000,17.000 L7.000,17.000 L7.000,14.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M14.000,14.000 L17.000,14.000 L17.000,17.000 L14.000,17.000 L14.000,14.000 Z" />
                                    </svg>
                                </a>
                            </li>
                            <li class="nav-item border">
                                <a class="nav-link p-0 height-38 width-38 justify-content-center d-flex align-items-center" id="pills-two-example1-tab" data-toggle="pill" href="#pills-two-example1" role="tab" aria-controls="pills-two-example1" aria-selected="false">
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="23px" height="17px">
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M-0.000,0.000 L3.000,0.000 L3.000,3.000 L-0.000,3.000 L-0.000,0.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M7.000,0.000 L23.000,0.000 L23.000,3.000 L7.000,3.000 L7.000,0.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M-0.000,7.000 L3.000,7.000 L3.000,10.000 L-0.000,10.000 L-0.000,7.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M7.000,7.000 L23.000,7.000 L23.000,10.000 L7.000,10.000 L7.000,7.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M-0.000,14.000 L3.000,14.000 L3.000,17.000 L-0.000,17.000 L-0.000,14.000 Z" />
                                        <path fill-rule="evenodd" fill="rgb(25, 17, 11)" d="M7.000,14.000 L23.000,14.000 L23.000,17.000 L7.000,17.000 L7.000,14.000 Z" />
                                    </svg>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>*@

                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-one-example1" role="tabpanel" aria-labelledby="pills-one-example1-tab">

                        <ul class="products list-unstyled row no-gutters row-cols-2 row-cols-lg-3 row-cols-wd-4 border-top border-left mb-6">
                            @{int i = -1;
                                foreach (var item in Model)
                                {
                                    i++;
                                    <li class="product col">
                                        <div class="product__inner overflow-hidden p-3 p-md-4d875">
                                            <div class="woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative">
                                                <div class="woocommerce-loop-product__thumbnail">
                                                    <a href="@Url.Action("ChiTietSach","Sach", new {@MaSach=item.MaSach})" class="d-block"><img style="width:240px; height:350px" src="@Url.Content("~/Images/book/" + item.Anh)" class="img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid" alt="image-description"></a>
                                                </div>
                                                <div class="woocommerce-loop-product__body product__body pt-3 bg-white">
                                                    <div class="text-uppercase font-size-1 mb-1 text-truncate"><a href="single-product-v1.html">Paperback</a></div>
                                                    <h2 class="woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark"><a href="single-product-v1.html">@item.TenSach</a></h2>
                                                    <div class="font-size-2  mb-1 text-truncate"><a href="https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/others/authors-single.html" class="text-gray-700">@item.TacGia</a></div>
                                                    <div class="price d-flex align-items-center font-weight-medium font-size-3">
                                                        @if (item.GiamGia == 0)
                                                        {
                                                            <span class="woocommerce-Price-amount amount">
                                                                @String.Format("{0:N0}", @item.GiaTriSach) 
                                                                <span class="woocommerce-Price-currencySymbol"> ₫</span>
                                                            </span>
                                                        }
                                                        else
                                                        {
                                                            <span class="woocommerce-Price-amount amount" style="width:100%;">
                                                                <span style="text-decoration: line-through; font-size:12px;">
                                                                    @String.Format("{0:N0}", @item.GiaTriSach) ₫
                                                                </span>
                                                                <span style="color:limegreen; float:right">
                                                                    Giảm @item.GiamGia%
                                                                </span>
                                                                <br />
                                                                @String.Format("{0:N0}", @ViewBag.GiaSach[i])
                                                                <span class="woocommerce-Price-currencySymbol"> ₫</span>
                                                            </span>
                                                        }
                                                    </div>
                                                </div>
                                                <div class="product__hover d-flex align-items-center">
                                                    <a href="@Url.Action("ThemSach_GioHang", "GioHang", new { @MaSach = item.MaSach, @Url = Request.Url.ToString() })" class="text-uppercase text-dark h-dark font-weight-medium mr-auto" data-toggle="tooltip" data-placement="right" title="" data-original-title="Thêm Vào Giỏ Hàng">
                                                        <span class="product__add-to-cart">+ Giỏ hàng</span>
                                                        <span class="product__add-to-cart-icon font-size-4"><i class="flaticon-icon-126515"></i></span>
                                                    </a>

                                                    @if (Session["TaiKhoan"] == null)
                                                    {
                                                        <a href="@Url.Action("DangNhap","NguoiDung")" class="h-p-bg btn btn-outline-primary border-0">
                                                            <i class="flaticon-heart"></i>
                                                        </a>
                                                    }
                                                    else
                                                    { 
                                                    <form method="post" action="@Url.Action("ThemVaoDanhSachYeuThich", "NguoiDung", new { @MaSach = item.MaSach, @Url = Request.Url.ToString()  })">
                                                        <button type="submit" class="h-p-bg btn btn-outline-primary border-0"><i class="flaticon-heart"></i></button>
                                                    </form>
                                                    }

                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                }
                            }


                        </ul>

                    </div>

                </div>

                @*<nav aria-label="Page navigation example">
                    <ul class="pagination pagination__custom justify-content-md-center flex-nowrap flex-md-wrap overflow-auto overflow-md-visble">
                        <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">Previous</a></li>
                        <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">1</a></li>
                        <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">2</a></li>
                        <li class="flex-shrink-0 flex-md-shrink-1 page-item active" aria-current="page"><a class="page-link" href="#">3</a></li>
                        <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">4</a></li>
                        <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">5</a></li>
                        <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">Next</a></li>
                    </ul>
                </nav>*@
            </div>
        </div>
    </div>
</div>

Views/Sach/SanPhamTheoLoai.cshtml
@using BookStore.Models;
@model List<Sach>
@{
    ViewBag.Title = ViewBag.TenTheLoai;
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="site-content space-bottom-3" id="content">
    <div class="container">
        <div class="col-12">
            <div id="primary" class="content-area order-2">

                <div class="shop-control-bar d-lg-flex justify-content-between align-items-center mb-5 text-center text-md-left">
                    <h3 style="padding:30px 0 0 30px;">Thể loại : @ViewBag.TenTheLoai</h3>
                </div>
                @{
                    if (ViewBag.lstSanPham == null)
                    {
                        <div class="tab-content" id="pills-tabContent">
                            <div class="tab-pane fade show active" id="pills-one-example1" role="tabpanel" aria-labelledby="pills-one-example1-tab">

                                <ul class="products list-unstyled row no-gutters row-cols-2 row-cols-lg-3 row-cols-wd-4 border-top border-left mb-6">
                                    @{int i = -1;
                                        foreach (var item in Model)
                                        {
                                            i++;
                                            <li class="product col">
                                                <div class="product__inner overflow-hidden p-3 p-md-4d875">
                                                    <div class="woocommerce-LoopProduct-link woocommerce-loop-product__link d-block position-relative">
                                                        <div class="woocommerce-loop-product__thumbnail">
                                                            <a href="@Url.Action("ChiTietSach","Sach", new {@MaSach=item.MaSach})" class="d-block"><img style="width:240px; height:350px" src="@Url.Content("~/Images/book/" + item.Anh)" class="img-fluid d-block mx-auto attachment-shop_catalog size-shop_catalog wp-post-image img-fluid" alt="image-description"></a>
                                                        </div>
                                                        <div class="woocommerce-loop-product__body product__body pt-3 bg-white">
                                                            <div class="text-uppercase font-size-1 mb-1 text-truncate"><a href="single-product-v1.html">Paperback</a></div>
                                                            <h2 class="woocommerce-loop-product__title product__title h6 text-lh-md mb-1 text-height-2 crop-text-2 h-dark"><a href="single-product-v1.html">@item.TenSach</a></h2>
                                                            <div class="font-size-2  mb-1 text-truncate"><a href="https://demo2.madrasthemes.com/bookworm-html/redesigned-octo-fiesta/html-demo/others/authors-single.html" class="text-gray-700">@item.TacGia</a></div>
                                                            <div class="price d-flex align-items-center font-weight-medium font-size-3">
                                                                @if (item.GiamGia == 0)
                                                                {
                                                                    <span class="woocommerce-Price-amount amount">
                                                                        @String.Format("{0:N0}", @item.GiaTriSach) 
                                                                        <span class="woocommerce-Price-currencySymbol"> ₫</span>
                                                                    </span>
                                                                }
                                                                else
                                                                {
                                                                    <span class="woocommerce-Price-amount amount" style="width:100%;">
                                                                        <span style="text-decoration: line-through; font-size:12px;">
                                                                            @String.Format("{0:N0}", @item.GiaTriSach) ₫
                                                                        </span>
                                                                        <span style="color:limegreen; float:right">
                                                                            Giảm @item.GiamGia%
                                                                        </span>
                                                                        <br />
                                                                        @String.Format("{0:N0}", @ViewBag.GiaSach[i]) 
                                                                        <span class="woocommerce-Price-currencySymbol"> ₫</span>
                                                                    </span>
                                                                }
                                                            </div>
                                                        </div>
                                                        <div class="product__hover d-flex align-items-center">
                                                            <a href="@Url.Action("ThemSach_GioHang","GioHang", new{@MaSach = item.MaSach , @Url = Request.Url.ToString()})" class="text-uppercase text-dark h-dark font-weight-medium mr-auto" data-toggle="tooltip" data-placement="right" title="" data-original-title="Thêm Vào Giỏ Hàng">
                                                                <span class="product__add-to-cart">+ Giỏ Hàng</span>
                                                                <span class="product__add-to-cart-icon font-size-4"><i class="flaticon-icon-126515"></i></span>
                                                            </a>
                                                            @if (Session["TaiKhoan"] == null)
                                                            {
                                                                <a href="@Url.Action("DangNhap","NguoiDung")" class="h-p-bg btn btn-outline-primary border-0">
                                                                    <i class="flaticon-heart"></i>
                                                                </a>
                                                            }
                                                            else
                                                            {
                                                                <form method="post" action="@Url.Action("ThemVaoDanhSachYeuThich", "NguoiDung", new { @MaSach = item.MaSach, @Url = Request.Url.ToString()  })">
                                                                    <button type="submit" class="h-p-bg btn btn-outline-primary border-0"><i class="flaticon-heart"></i></button>
                                                                </form>
                                                            }
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                        }
                                    }


                                </ul>

                            </div>

                        </div>
                        @*<nav aria-label="Page navigation example">
                            <ul class="pagination pagination__custom justify-content-md-center flex-nowrap flex-md-wrap overflow-auto overflow-md-visble">
                                <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">Previous</a></li>
                                <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">1</a></li>
                                <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">2</a></li>
                                <li class="flex-shrink-0 flex-md-shrink-1 page-item active" aria-current="page"><a class="page-link" href="#">3</a></li>
                                <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">4</a></li>
                                <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">5</a></li>
                                <li class="flex-shrink-0 flex-md-shrink-1 page-item"><a class="page-link" href="#">Next</a></li>
                            </ul>
                        </nav>*@
                    }
                    else
                    {
                        <h4 style="text-align:center;">Không có sách thuộc thể loại này </h4>
                    }
                }
            </div>
        </div>
    </div>
</div>

Views/Sach/TheLoaiPartial.cshtml
@using BookStore.Models;
@model List<TheLoai>

@foreach (var item in Model)
{
    <li>
        <a href="@Url.Action("SanPhamTheoLoai", "Sach", new {@MaTheLoai = item.MaTheLoai})" class="dropdown-item link-black-100">@item.TenTheLoai</a>
    </li>
}